### ISSUE TITLE
NeuGen Executables (OSX > 10.10)

### ISSUE THREAD

**Issue by miho** [NeuroBox3D/NeuGen#28]
Currently, NeuGen does not run out of the box, i.e., pressing the *run* button in NetBeans causes reproducible errors (at least on macOS 10.12, JDK 1.8.x, devel-branch):

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Application is not launched.
	at org.jdesktop.application.Application.checkApplicationLaunched(Application.java:692)
	at org.jdesktop.application.Application.getInstance(Application.java:666)
	at org.neugen.gui.NeuGenProject.initComponents(NeuGenProject.java:139)
	at org.neugen.gui.NeuGenProject.<init>(NeuGenProject.java:92)
```
 

Running NeuGen with the `run.sh`script works though. The problem with the run-Script, however, is that it does not have access to the correct classpath without manual configuration. The scripts themselves are problematic too: for example, they do only work if they are called from the correct directory since they can't figure out their own location on the filesystem. At least the documentation should be updated to allow new users/developers to run NeuGen without too much guess-work.

Rather than improving the current scripts, it might be a good idea to join forces with our VRL-Studio IDE where most problems regarding executables and installation have been solved. And we already use it as part of the NeuroBox toolchain anyway.

What do you think? Let me know if you need help.

**Comment by bsumirak** [comment]
Interesting.
It worked well out of the box for me, when I tested it three days ago (but Mac OS 10.9). So it could really be OS (version)-specific.
Had to »clean and build« before running though.

How exactly do you mean »join forces with our VRL-Studio IDE«? NeuGen as a VRL plugin?
M.



Am 01.12.2016 um 13:43 schrieb Michael Hoffer <notifications@github.com>:

**Comment by miho** [comment]
> It worked well out of the box for me, when I tested it three days ago (but Mac OS 10.9)

The problem is that the scripts prevents certain potential errors, by setting the ext-classpath etc. Running NeuGen from NetBeans does not specify these settings which makes it inconsistent to the run scripts. On newer version of macOS (and depending on the ext-classpath) it definitely doesn't work.

> How exactly do you mean »join forces with our VRL-Studio IDE«? NeuGen as a VRL plugin?

It could be a regular plugin or a tool plugin (accessible via Tools-Menu) that just opens the the original NeuGen UI. Then NeuGen wouldn't need its own run-scripts etc. It could just reuse the complete OS dependent logic. Even updates could be delivered via NeuroBox flavored VRL.

**Comment by miho** [comment]
I just realized that work on this has already be started. NeuGen contains VRL.jar as dependency and adds a Tool-Menu entry for VRL. It seems to work.

**Comment by stephanmg** [comment]
@miho good idea. I've already set-up a regular plugin VRL-NeuGen-Plugin for VRL-Studio with some preliminary functionality. It certainly needs to be enhanced.

**Comment by stephanmg** [comment]
Realizing this is a bug in OSX > 10.10 I will try to address this issue now...

**Comment by stephanmg** [comment]
Run NeuGen through Netbeans by Run File NeuGenApp.java.
